export const orderStatus = [
  'WAITING_FOR_PRICE',
  'WAITING_FOR_DP',
  'WAITING_FOR_ORDER_CONFIRMATION_FROM_ADMIN',
  'IN_PROCESS',
  'READY_TO_DELIVERY',
  'IN_DELIVERY',
  'WAITING_FOR_FULL_PAYMENT',
  'WAITING_FOR_PAYMENT_CONFIRMATION_FROM_ADMIN',
  'COMPLETE',
  'CANCEL'
]

export const orderDetailStatus = [
  'CUTTING',
  'SEWING',
  'FINISHING',
  'PACKING',
  'COMPLETE',
  'ORDER_COMPLETE'
]
